name: Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit

  release:
    runs-on: ubuntu-22.04
    name: "Build and release action"
    needs: [build]
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
          persist-credentials: true
      - name: Configure git
        uses: smartlyio/github-actions@git-init-userinfo-v1
      - name: Release flow
        uses: smartlyio/github-actions@release-action-node-v1
        with:
          dry_run: true
          use_yarn: true
          token: "${{ secrets.GITHUB_TOKEN }}"
